In [2]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 19.8 MB 720 kB/s eta 0:00:01
You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [6]:
pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 2.1 MB 4.6 MB/s eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install pandas numpy matplotlib seaborn sklearn

Note: you may need to restart the kernel to use updated packages.


In [1]:
! pip install pandas numpy matplotlib seaborn sklearn

  Using cached sklearn-0.0.post4.tar.gz (3.6 kB)
  Preparing metadata (setup.py) ... done
  Created wheel for sklearn: filename=sklearn-0.0.post4-py3-none-any.whl size=2950 sha256=c5c589bff2227a35d2bdcff5a19767ad79d5eafd458fd91d963f07cdc5be12c8
  Stored in directory: /Users/nozomitoujou/Library/Caches/pip/wheels/de/6a/05/7cad3fe50c04cfcba9f13bf25766f6fa85764e4f76f5c4fd98
Successfully built sklearn


In [4]:
import numpy as np
import seaborn as sns

In [23]:
# note: have to click "raw" on github to get this url
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/JinL-Zhang/Schulich_MBAN-6110/main/messy_data.csv")
df

Age       Income  Gender Product  Quantity
0     56  59544.57663  Female       D         3
1     46  36399.18997  Female     NaN         1
2     32  57140.63881  Female       D         2
3     60  69554.91903    Male       C         5
4     25  53173.80518  Female       D         2
..   ...          ...     ...     ...       ...
100   61  37341.55459    Male       D         5
101   55  35516.63492  Female       A         3
102   31  53254.05089    Male       B         2
103   21          NaN    Male       B         2
104   60  69554.91903    Male       C         5

[105 rows x 5 columns]

In [14]:
# note: data type of object may be string 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105 entries, 0 to 104
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       105 non-null    int64  
 1   Income    94 non-null     float64
 2   Gender    105 non-null    object 
 3   Product   100 non-null    object 
 4   Quantity  105 non-null    int64  
dtypes: float64(1), int64(2), object(2)
memory usage: 4.2+ KB


In [19]:
# note: describe only show numeric features' metadata
# To show data info about all features (numeric + categorical), use attribute "include = 'all'"
df.describe(include = 'all')

# Ex: Most frequent product is D, with frequency = 28

Age         Income  Gender Product   Quantity
count   105.000000      94.000000     105     100  105.00000
unique         NaN            NaN       2       4        NaN
top            NaN            NaN  Female       D        NaN
freq           NaN            NaN      58      28        NaN
mean     42.076190   52867.862808     NaN     NaN    3.20000
std      15.940813   29896.579420     NaN     NaN    1.44382
min      18.000000   20901.331720     NaN     NaN    1.00000
25%      31.000000   37814.315255     NaN     NaN    2.00000
50%      41.000000   48760.369705     NaN     NaN    3.00000
75%      55.000000   61644.277868     NaN     NaN    5.00000
max     120.000000  300000.000000     NaN     NaN    5.00000

In [13]:
df.isnull().sum()

Age          0
Income      11
Gender       0
Product      5
Quantity     0
dtype: int64

## Practice numpy

In [2]:
# Initiate a numpy array by using the regular python list
# operations on numpy array are element-wise 
import numpy as np
a = [3,2]
b = [3,4]
np_a = np.array(a)
np_b = np.array(b)
np_a * np_b


array([9, 8])

In [3]:
np_a = np.array([1,"yes",True])

# since numpy array only hold one type of value, they will all be casted to string in this case

np_a

array(['1', 'yes', 'True'], dtype='<U21')

In [4]:
# a trick to get values > 20 in a np array
np_a = np.array([1, 3, 4, 5])
np_a[np_a>1] # because np_a>1 will generate a boolean array [False,  True,  True,  True]

array([3, 4, 5])

In [6]:
# note that in np arrary, True is converted to 1, False is converted to 0.
np.array([True, 1, 2]) + np.array([3, 4, False])

array([4, 5, 2])